'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QuanLyCuaHangMT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0bba15392decda38135e0ba1465dac2b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0bba15392decda38135e0ba1465dac2b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1025_cach_cai_hinh_nen_may_tinh_vo_cung_don_gian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1025_cach_cai_hinh_nen_may_tinh_vo_cung_don_gian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property abstract_square_interface_modern_background_concept_fingerprint_digital_scanning_visual_security_system_authentication_login_vector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-square-interface-modern-background-concept-fingerprint-digital-scanning-"& _ 
                        "visual-security-system-authentication-login-vector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background_chill_nhe_nhang_085528030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background-chill-nhe-nhang_085528030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background_nhe_nhang_dep_tuyet_085535337() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background-nhe-nhang-dep-tuyet_085535337", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background_xanh_nhe_nhang_tinh_te_cho_PowerPoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background-xanh-nhe-nhang-tinh-te-cho-PowerPoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background_xanh_nhe_nhang_tinh_te_cho_PowerPoint1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background-xanh-nhe-nhang-tinh-te-cho-PowerPoint1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ban_phim_laptop_bi_loi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ban-phim-laptop-bi-loi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cach_ket_noi_man_hinh_may_tinh_de_ban_voi_laptop_may_tinh_de_ban_pc_win_10_win_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cach-ket-noi-man-hinh-may-tinh-de-ban-voi-laptop-may-tinh-de-ban-pc-win-10-win-11"& _ 
                        "", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hinh_nen_dep_mau_trang_104324637() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hinh-nen-dep-mau-trang_104324637", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hinh_nen_hoa_cuc_trang_1_11_10_28_00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hinh-nen-hoa-cuc-trang-1-11-10-28-00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hinh_nen_may_tinh_de_thuong_nhat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hinh-nen-may-tinh-de-thuong-nhat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hinh_nen_nhe_nhang_cute_ve_con_voi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hinh-nen-nhe-nhang-cute-ve-con-voi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hinh_nen_powerpoint_xanh_la_cay_nhe_nhang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hinh-nen-powerpoint-xanh-la-cay-nhe-nhang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_cartoon_computer_illustration_png_image_6567230() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-cartoon-computer-illustration-png-image_6567230", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngtree_illustration_of_a_3d_render_showcasing_a_concept_of_web_ui_picture_image_13289194() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngtree-illustration-of-a-3d-render-showcasing-a-concept-of-web-ui-picture-image_"& _ 
                        "13289194", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property th() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
